---
- name: Install Dependencies
  yum:
    name: ['git', 'java-1.8.0-openjdk']
    state: present
  become: yes
- name: Install Additional Dependencies
  yum:
    name: '{{ jenkins_additional_packages | default([]) }}'
    state: present
  become: yes