---
- name: Install Dependencies
  yum:
    name: '{{ vm_packages }}'
    state: present
  become: yes
- name: Install Additional Dependencies
  yum:
    name: '{{ jenkins_additional_packages | default([]) }}'
    state: present
  become: yes