---
- include_tasks: 'extra/wait.yml'
- name: Run Jenkins Script
  jenkins_script:
    script: '{{ item.script }}'
    user: '{{ jenkins_admin_username }}'
    password: '{{ jenkins_ephemeral_admin_password }}'
  with_items: '{{ jenkins_default_scripts | union(jenkins_init_scripts|default([])) }}'
