- name: Wait for Jenkins to Create Admin Password
  wait_for:
    path: '/var/lib/jenkins/secrets/initialAdminPassword'
  when: jenkins_installed is changed
- block:
  - name: Check Initial Admin Password File Exists
    stat:
      path: '/var/lib/jenkins/secrets/initialAdminPassword'
    register: jenkins_initial_admin_password_file
  - block:
      - name: Get Jenkins Admin Password
        slurp:
          src: '/var/lib/jenkins/secrets/initialAdminPassword'
        become: yes
        register: jenkins_initial_admin_password_file_slurp
      - name: Set Jenkins Initial Admin Password Fact
        set_fact:
          jenkins_initial_admin_password: '{{ jenkins_initial_admin_password_file_slurp.content|b64decode|trim }}'
    when: jenkins_initial_admin_password_file.stat.exists
- name: Set Jenkins Admin Password Fact
  set_fact:
    jenkins_ephemeral_admin_password: '{{ jenkins_initial_admin_password|default(jenkins_admin_password) }}'
